### ISSUE TITLE
Hur hanteras bilder och andra binära filer i Git?

### ISSUE THREAD

**Issue by kamar535** [simonlovgren/introit-16#106]
Hur funkar det att hantera binära filer, till exempel bilder i git. 

Kan jag ändra en bild, dvs byta ut en bild mot en ny version och fortfarande hitta den gamla version i Git?

**Comment by simonlovgren** [comment]
Det skall fungera på samma sätt med skillnad att du inte kan se diff på binära filer, utan den uppdaterar hela binära filen om jag minns rätt.

Om du ex. browsar repot som en gammal kommit skall alla binära filer som fanns då ligga där.
