### ISSUE TITLE
Åtkomst till handledarsidorna

### ISSUE THREAD

**Issue by kamar535** [simonlovgren/introit-16#107]
Användarnamn och lösenord för åtkomst till handledarsidorna på den driftsatta siten?

**Comment by kamar535** [comment]
Hittar lista med användarnamn och lösen för handledarna https://docs.google.com/spreadsheets/d/1yc3d_OJSf60M2WfHtvJohHiL-Vj5GurQjO4piOdW6sQ/edit#gid=0 dock ej för (de förmodade) testanvändarna `handledare1`, `handledare2` och `handledare3`.

**Comment by simonlovgren** [comment]
Det var den lista jag använde för att generera pinkoder till samtliga handledare. testanvändarna ligger fortfarande kvar men andra konton kan lätt läggas till och de tas bort.

**Comment by kamar535** [comment]
Lösenord till testkonton?
