### ISSUE TITLE
Gamla (?) branches

### ISSUE THREAD

**Issue by simonlovgren** [simonlovgren/introit-16#109]
@Kurogamu kan branchen [`uppgifter-studenttjanster`](/simonlovgren/introit-16/tree/uppgifter-studenttjanster) raderas?  
_Den verkar bara innehålla den gamla (alternativa) inluppen för studenttjänster._

***

@kamar535  kan branchen [`om-inlämning-och-framsteg`](/simonlovgren/introit-16/tree/om-inlämning-och-framsteg) raderas?  
_Den verkar inte ha någon diff mot `master`._

**Comment by simonlovgren** [comment]
ping @Kurogamu @kamar535

**Comment by Kurogamu** [comment]
Rensa på, har inga aktiva branches.

**Comment by kamar535** [comment]
Ja, ta bort branch om-inlämning-och-framsteg.
