### ISSUE TITLE
Sammanställ first-draft uppgiftsmaterial

### ISSUE THREAD

**Issue by simonlovgren** [simonlovgren/introit-16#16]
- [x] Studenttjänster
- [x] Excel
- [x] Linux
- [x] Terminalen
- [x] Latex
- [x] MATLAB
- [x] Git
- [x] ~~Editorer~~

**Comment by kamar535** [comment]
Hur går det med detta, finns det några drafts på uppgifter?

**Comment by Kurogamu** [comment]
Ja, de som har blivit mergade finns i master.
