### ISSUE TITLE
Förbered föreläsningsmaterial

### ISSUE THREAD

**Issue by simonlovgren** [simonlovgren/introit-16#2]
- [x] Studenttjänster
- [x] Latex
- [x] Excel
- [x] MATLAB
- [x] Linux
- [x] Terminalen
- [x] Git

**Comment by simonlovgren** [comment]
@Kurogamu skall du, jag eller båda sätta sig med föreläsningsmaterial till studenttjänster? Första handledninstillfället är imorgon kl. 15 för it/dv

**Comment by Kurogamu** [comment]
NNGGHGH

**Comment by Kurogamu** [comment]
Woop
