### ISSUE TITLE
Byt externa länkar till att anv. shortcode {{< extlink >}}

### ISSUE THREAD

**Issue by simonlovgren** [simonlovgren/introit-16#40]

**Comment by kamar535** [comment]
Går det att göra detta automatiskt på något sätt, kanske med hjälp av någon callback vid renderingen? 

Alternativt skapa ett skript som spindlar hela siten och byter ut externa länkar till {{< extlink >})?

**Comment by simonlovgren** [comment]
detta får vi se till att göra det sista vi gör, ifall man råkar lägga till externa länkar med standardsyntax när vi redigerar materialet
