### ISSUE TITLE
Fixa enligt Karls kommentarer 16-08-16

### ISSUE THREAD

**Issue by Kurogamu** [simonlovgren/introit-16#41]
- [x] Timestamp 
- [x] Powered by Hugo
- [x] Favicon
- [ ] Navigering
- [x] Excel
- [x] Editorer
- [x] Matlab
- [x] Latex
- [x] Studenttjänster
- [x] Terminalen
- [x] Linux
- [x] Git

**Comment by simonlovgren** [comment]
Frågan är hur man kan lägga upp:
> Bra om det tydligt framgår exakt vart i hierarkin man befinner sig även när man skrollat ner lite. Som det är nu finns ingen info i skrift om vilken modul och underavdelning (information eller uppgifter) man befinner sig i topp-meny (förutom färg).

då det redan i mobilläge är tunnt om realestate både i skärm och menyrad...
@Kurogamu @kamar535 har ni några idéer om hur man skulle kunna lägga upp detta?

**Comment by kamar535** [comment]
Kika på t.ex. https://gohugo.io/overview/introduction/ där det responsiva gränssnittet automatiskt visar/döljer en meny till vänster, kanske kan detta vara ett alternativ?
