### ISSUE TITLE
Navigering till ankarlänkar och topp-menyn

### ISSUE THREAD

**Issue by kamar535** [simonlovgren/introit-16#46]
Vid navigering till en ankarlänk, till exempel till en H2 hamnar elementet med ankaret bakom topp-menyn och syns alltså inte vilket är lite förvirrande. 

Finns det något sätt att lösa detta på? Javascript? Byta sättet som topp-menyn renderas på så att den inte flyter ovanpå?

**Comment by simonlovgren** [comment]
Detta är ett problem som uppstår iom. follow-scroll/sticky meny och om den inte renderas över resten av sidan kommer dess länkar inte gå klicka på. Då sidan är responsive (och inte en fast bredd/storlek) är det inte lätt bara flytta menyn till sidan eller liknande, så frågan är om det går offset:a ankarlänkarna eller liknande.

Jag undersöker detta vidare.
