### ISSUE TITLE
Skapa innehållsförteckning/navigering automatiskt

### ISSUE THREAD

**Issue by kamar535** [simonlovgren/introit-16#47]
Om det inte redan är möjligt vore det mycket praktiskt om innehållsförteckning/navigering på varje sida kan skapas automatiskt.

**Comment by Kurogamu** [comment]
Vi testade hugos inbyggda kommando för det, men den gav felaktig formatering.

Det finns ett fulhack skrivet för Linux, via scriptet `tocgen.sh`. Den kan generera en innehållsförteckning baserat på nyckelord (i vårt fall `#*# Innehåll` (via en himla massa regex-uttryck), men kommandona som den kör är visst Linux-specifika versioner av `sed` och `awk`, så det blir heltrasigt på Mac.

**Comment by simonlovgren** [comment]
Denna blir en del av #41 eller #35 (navigering alt sticky-toc)
