### ISSUE TITLE
Uppdatering av lastmod

### ISSUE THREAD

**Issue by kamar535** [simonlovgren/introit-16#48]
Är det tänkt att lastmod skall uppdateras manuellt av den skribent som uppdaterar en sida?

Om ja, i Emacs, går det att sätta in timestamp på lämpligt format med något kommando?

**Comment by Kurogamu** [comment]
I dagsläget - ja. @simonlovgren har ordnat ett skript som fixar detta: `lastmod_update.py`

**Comment by simonlovgren** [comment]
Det finns inget inbyggt system i hugo som kan uppdatera lastmod-parametern automatiskt, tyvärr.
Se PR #42 för info om hur scriptet används, eller skriv `./lastmod_update.py --help` för hjälptext.

**Comment by simonlovgren** [comment]
Kan tillägga att en tanke är att lägga till lastmod_update.py som en del av make-regeln för 'make all', så körs den 'automatiskt' varje gång man bygger för live-sidan

**Comment by simonlovgren** [comment]
Lagt till att scriptet automatiskt körs med make-all. Värt att notera är att timestamp på filerna ändras till 'nuvarande tid' av git om ändringar synkas från remote (med andra ord inte timestampen när någon skickade upp en commit, utan timestamp när någon hämtat hem ändringarna) eller git av någon anledning touch:ar en fil.

lastmod-parametern kommer därmed främst visa vilket datum filerna byggdes för release.

Fixad i 66174b8
