### ISSUE TITLE
E-postadresser 

### ISSUE THREAD

**Issue by kamar535** [simonlovgren/introit-16#52]
Vilka e-postadresser behövs?

Vi har sedan tidigare diskuterat projektledare@introduktion-till-datorer.it.uu.se

Vart skall studenter vända sig med frågor om materialet? Vilka skall besvara dessa frågor?

En e-postadress per utbildning (kurs) som primärt bevakas av handledare för respektive utbildning, till exempel:

E/EI-2016@introduktion-till-datorer.it.uu.se
ES-2016@introduktion-till-datorer.it.uu.se
F-2016@introduktion-till-datorer.it.uu.se
IT/KandDv-2016@introduktion-till-datorer.it.uu.se
KandMa-2016@introduktion-till-datorer.it.uu.se
MI-2016@introduktion-till-datorer.it.uu.se
Q-2016@introduktion-till-datorer.it.uu.se
STS-2016@introduktion-till-datorer.it.uu.se
W-2016@introduktion-till-datorer.it.uu.se

Fördelen med att ange både utbildning och årtal är att denna information ofta saknas när studenter skickar e-post angående Introduktion till datorer.  

Blir det krångligt med många olika e-postadresser?

**Comment by simonlovgren** [comment]
Jag tror det kan vara idé att ha en per program och år som studenterna kan maila till.

När vi planerade schemaläggnigen satte vi upp, för nästan alla klasser, en tabell där vi kunde hitta två klasser som inte krockade med varandra eller hade handledningstillfällen på samma dag. Detta innebär att för de flesta handledare har de två klasser från olika program, men jag antar att det inte skulle vara något problem om flera handledare får mailet och att när de svarar CC:ar 'klass-adressen' så alla andra handledare ser att frågan besvarats?

**Comment by kamar535** [comment]
Går ej att skapa adresser med domän `introduktion-till-datorer.it.uu.se`, endast med domänen `it.uu.se`.

Jag undersöker om vi istället kan skapa följande funktionsadresser: 

- projektledare-introduktion-till-datorer@it.uu.se
- E/EI-2016-introduktion-till-datorer@it.uu.se
- ES-2016-introduktion-till-datorer@it.uu.se
- F-2016-introduktion-till-datorer@it.uu.se
- IT/KandDv-2016-introduktion-till-datorer@it.uu.se
- KandMa-2016-introduktion-till-datorer@it.uu.se
- MI-2016-introduktion-till-datorer@it.uu.se
- Q-2016-introduktion-till-datorer@it.uu.se
- STS-2016-introduktion-till-datorer@it.uu.se
- W-2016-introduktion-till-datorer@it.uu.se

**Comment by kamar535** [comment]
Begäran om funktionsepostadresser gjord i Bugzilla https://www.it.uu.se/internt/web/bugzilla/show_bug.cgi?id=9320

**Comment by simonlovgren** [comment]
@kamar535 jag såg att de stängt ticketen ang. mailadresser. Har du fått/kan du fixa en lista över vilka mailadresser som gäller?

Det sista innan jag skapar en PR för första versionen av 'vad är intro till datorer'-sidan och programspecifika sidor är att lägga in korrekta mailadresser på varje programsida.

**Comment by kamar535** [comment]
@simonlovgren Lista med skapade funktionsadresser: https://docs.google.com/spreadsheets/d/1L9F9XHle6N6f5L9f49ywotsXzRgKe3FBV6jh-y_pkZA/edit#gid=0

Jag aktiverade adresserna i går och väntar fortfarande på någon form av kvittens med information om att kontona skapats och hur jag går vidare för att konfigurera dessa.

**Comment by kamar535** [comment]
Alla funktionskonton är nu uppe och snurrar. 

Det går att läsa och skicka e-post mha https://mail.uu.se/ och inloggningsuppgifter finns här https://docs.google.com/spreadsheets/d/1L9F9XHle6N6f5L9f49ywotsXzRgKe3FBV6jh-y_pkZA/edit#gid=0

Tyvärr går det inte att vidarebefordra till adresser som inte tillhör anställda vid UU. 

Dock bör det gå att lägga till kontot och läsa med de flesta vanliga e-postklienter, jag har till exempel testat att lägga till kontot projektledare-introduktion-till-datorer@it.uu.se och W-2016-introduktion-till-datorer@it.uu.se och till Thunderbird. 

![screen shot 2016-08-26 at 16 20 45](https://cloud.githubusercontent.com/assets/8029215/18008627/1e44c454-6ba9-11e6-9a47-97ce0e5ddd1b.png)
![screen shot 2016-08-26 at 16 20 38](https://cloud.githubusercontent.com/assets/8029215/18008626/1e416764-6ba9-11e6-8732-2896d864ed71.png)
![screen shot 2016-08-26 at 16 22 15](https://cloud.githubusercontent.com/assets/8029215/18008674/4bc5e1ce-6ba9-11e6-8aed-05d49ba0168c.png)

**Comment by simonlovgren** [comment]
@kamar535 hur gör vi för utdelning av lösenord till handledarna? Ska vi maila ut inloggen till de som handleder programmet/n det/de programmet/ns inlogg?

**Comment by kamar535** [comment]
Ja, e-posta ut uppgifter till berörda handledare funkar bra.

**Comment by simonlovgren** [comment]
Då gör vi så

**Comment by simonlovgren** [comment]
skickat till samtliga handledare, stänger issue
