### ISSUE TITLE
Bygga ut med frivilliga fördjupnade uppgifter

### ISSUE THREAD

**Issue by kamar535** [simonlovgren/introit-16#55]
Vore mycket bra om vi kunde bygga ut med frivilliga fördjupningar för de som blir klara snabbt. Dessa behöver inte vara lika detaljerade utan det kanske räcker med några olika förslag samt länkar till lämplig information. Kanske skall detta ligga som en separat sida per modul för att göra det extremt tydligt att det är friviiligt, eller så lägger vi det som ett avslutande avsnitt sist på varje uppgiftssida.

**Comment by simonlovgren** [comment]
Finns det något man kan använda sedan tidigare eller är det en helt ny grej?

**Comment by Kurogamu** [comment]
Ska det läggas upp som extra inlämning?

Eftersom det börjar bli ont om tid tror jag mer på att finslipa material som finns i första hand och istället lägga fördjupande uppgifter till nästa år.

Däremot kan vi ha länkar till vidare läsning i slutet av varje infosida (i samma stil som Git-modulen)

**Comment by kamar535** [comment]
Absolut inte lägga till som extra inlämningar. 

Jag tänker mer något som pekar vidare för de som blir klara snabbt. Kan mycket väl räcka med några länkar för vidare läsning. Kanske komplettera med några förslag till exakt vad som kan vara bra att lära sig på egen hand plus länkar till relaterad information.
