### ISSUE TITLE
Demo-konton för Linux

### ISSUE THREAD

**Issue by kamar535** [simonlovgren/introit-16#57]
Hur många test/demo-konton för Linux behöver ni?

Om möjligt, hur vill ni att dessa skall namnges?

Kanske är det möjligt att få abcd1234 om det inte råkar finnas någon befintlig student med detta användarnamn. 

Kanske något i stil med demo-1, demo-2, demo-3?

**Comment by Kurogamu** [comment]
Det viktigaste vore att den följer samma mönster som studentkontona, så det blir glasklart vad som ska skrivas.
`abcd1234` skulle vara bäst, eftersom det innebär att vi inte behöver skriva om några beskrivningar. Annars går det väl lika bra med `xxxx0000` och liknande.

**Comment by kamar535** [comment]
Begäran om test/demo-konton gjord, se https://www.it.uu.se/internt/web/bugzilla/show_bug.cgi?id=9318

**Comment by kamar535** [comment]
Joel Fredriksson meddelar: 

> Testkontona måste börja med 
> 
>   it-
> 
> eftersom vi måste lägga in dom i det centrala AD:t för att dom ska fungera på samma sätt som student-kontona.
> 
> Så it-xxxx0000, it-xxxx0001 .... är möjligt.

**Comment by Kurogamu** [comment]
`it-namn` kanske skulle bli bra?
Om samma konto kan användas av flera samtidigt skulle det gå att använda till handledningen.

**Comment by Kurogamu** [comment]
Inkluderar det förresten stöd för studentportalen? För det vore grymt att kunna ändra beskrivningarna så att inte mitt användarnamn står där :)

**Comment by kamar535** [comment]
Efter diskussion https://www.it.uu.se/internt/web/bugzilla/show_bug.cgi?id=9318 blir det it-test-00, it-test-02 etc. Men jag kan försöka få igenom it-demo-00, it-demo-01 etc om tanken är att dessa är tänkt att användas för live-demo av handledare. 

Hur många demo-konton behövs?

**Comment by kamar535** [comment]
TIPS: Då jag använder mitt eget Linux-konto för att ta screenshots mm brukar jag sätta om prompten till `PS1='abcd1234@\u:\w\$ '` direkt i terminalen.

**Comment by kamar535** [comment]
Joel meddelar:

> Kontona är redan skapade, jag tänker inte gör om dom eftersom det är en helt
> manuell procedur just nu.
> 
> Dom finns att hämta i jourrummet (4118b).
> 
> Kontona expirerar 1 november.

Medtag legitimation.

**Comment by simonlovgren** [comment]
Godt, vi hämtar ut under morgondagen!

**Comment by simonlovgren** [comment]
(update) Konton hämtades ut i torsdags.
