### ISSUE TITLE
Git/Uppgifter

### ISSUE THREAD

**Issue by kamar535** [simonlovgren/introit-16#58]
Inom ramen för kursen 1DT051 funderar jag på att publicera all kod för momentet om programmering (Python) i ett repo på GitHub (och inte som vanligt i form av en tar-boll). 

Vore kanske bra om det fanns en inledande uppgift som enbart går ut på att clona ett befintligt repo samt kanske göra några enkla operationer (add, commit, checkout (revert to old commit) på det clonade repot.

**Comment by kamar535** [comment]
Blir det en konflikt om filen urval.txt har samma innehåll i båda grenarna (master och mitt-urval)?

**Comment by simonlovgren** [comment]
Det skulle definitivt kunna vara en grej om man sätter upp ett repo med filen kurser.txt eller liknande så de klonar det ist. för att skapa det själva.

Jag har inte testat det, men i och med att båda branches har ändrat i filen tror jag det fortfarande blir en konflikt.

**Comment by simonlovgren** [comment]
Tillagt via PR #75
