### ISSUE TITLE
Lista med personuppgifter för handledare

### ISSUE THREAD

**Issue by kamar535** [simonlovgren/introit-16#60]
Jag behöver en lista med personuppgifter för samtliga handledare. 

Enklast om listan finns i Google Drive. Listan behöver innehålla följande kolumner:

- Förnamn
- Efternamn
- Studentkonto (användarnman på formen abcd1234)
- Personnummer (även om det inte är helt lämpligt att hantera detta i Google Drive)
- Passerkortsnummer

**Comment by kamar535** [comment]
Hur går det med listan?

ASAP behöver jag veta personuppgifter enligt ovan för de som kommer handleda och rätta uppgifter för ES så att jag förhoppningsvis kan ordna med inlämning via systemet Fronter på SLU.

**Comment by kamar535** [comment]
Bra om listan blir klar så fort som möjligt och inte vänta till meet and great på torsdag 25/8 då jag behöver skicka listan vidare så att handledarna kan ges nödvändiga rättigheter i Studentportalen.

**Comment by simonlovgren** [comment]
Vi har inte fått svar från samtliga tillsatta ännu och vi har fått två personer som tackat nej efter de blivit tillsatta. Det går absolut göra ett google-form de kan fylla i och vi kan skicka ut det.

Vilka rättigheter i studentportalen? Det senaste vi hörde var att de inte kunde få tillgång till studentportalen utan att rättning m.m. skulle ske via mailande av inluppar?

**Comment by kamar535** [comment]
Jag har fått löfte om att det skall gå att ordna så att studenter får rättigheter att hantera framsteg på enskilda kurser. Men om det visar sig att det trots detta inte går att ordna så får vi falla tillbaka på lösningen med en mellanhand som skickar ut arkiv med inlämnade uppgifter.

**Comment by simonlovgren** [comment]
ok

**Comment by kamar535** [comment]
Är handledare för ES redan tillsatta? SLU meddelar att det är lite bökigt att fixa tillgång för utomstående till Fronter (deras motsvarighet till Studentportalen) och vill därför att vi kan skicka en en lista med personer som behöver åtkomst så snart som möjligt.

**Comment by simonlovgren** [comment]
Två av fyra har svarat och jag har skickat ut påminnelsemail då det verkar som vissa fått det taggat som skräppost

**Comment by simonlovgren** [comment]
Flera av handledarna har svarat på formuläret och vi kommer be de som inte svarat innan torsdag om uppgifterna under meet & greet.
