### ISSUE TITLE
Obligatoriska moduler

### ISSUE THREAD

**Issue by simonlovgren** [simonlovgren/introit-16#64]
Vi behöver få in vilka moduler som skall vara obligatoriska för samtliga program. Nedan i checklistan är ifyllt alla program vi fått modulval från, övriga behöver vi få reda på asap.

- [x] E/EI
- [x] ES
- [x] F
- [x] IT/KandDV
- [x] KandMa
- [x] MI
- [x] Q
- [x] STS
- [x] W

**Comment by simonlovgren** [comment]
@kamar535 har vi någon aning om vad kvarvarande program vill ha för obligatoriska moduler?

**Comment by kamar535** [comment]
E-post skickat till program- och kursansvariga för ES, F och STS.

**Comment by kamar535** [comment]
- STS Vill ha Excel och Matlab.
- ES-studenterna ska ha alla tre moduler. För ES finns alltså  totalt fem tillfällen schemalagda, där det sista tillfället är uppsamling.

**Comment by kamar535** [comment]
Olov Ågren (programansvarig) meddelar: 

> Matlab och Excel för teknisk fysik (Latex är helt onödigt, kan ju lösas med word eller annat).

**Comment by kamar535** [comment]
Undrar om alla lärare på kurser som läses av F håller med om Olov Ågrens slutsats :-)

**Comment by simonlovgren** [comment]
Tvivlar på det, men eftersom vi fått svar har vi ngt att gå efter i alla fall.

**Comment by kamar535** [comment]
Precis, vi kör enligt Olov Ågrens beslut. Jag tänkte mest på att han troligen inte har kollat med hur behovet av LaTex faktiskt ser ut på F.
