### ISSUE TITLE
Nybörjarenkät

### ISSUE THREAD

**Issue by kamar535** [simonlovgren/introit-16#65]
Från Björn Victor, 

> I samband med höstens programstarter inbjuder Teknisk-naturvetenskapliga fakulteten som vanligt till en enkät för våra programnybörjare. Medverkan i enkäten är frivillig, både för programmen och för studenterna, men eftersom den är en viktig källa till kunskap om våra studenter och deras väg hit till oss hoppas vi förstås att så många som möjligt vill vara med.

> Enkätsvaren sammanställs och analyseras av TUR (Teknisk-naturvetenskapliga fakultetens universitetspedagogiska råd). Resultaten presenteras bland annat för utbildningsnämnderna och TekNat Samverkan. För program där svarsfrekvensen blir tillräckligt hög kommer det även att finnas möjlighet att få programspecifika rapporter.

> Olika program väljer olika lösningar för hur och när enkäten genomförs. Målet är dock att nybörjarna ska ges möjlighet att besvara enkäten under de första studieveckorna. På program som deltar i den datorintroduktion som genomförs av institutionen för informationteknologi ingår Nybörjarenkäten där.

> Årets enkät nås via  http://tur.it.uu.se/index.php/survey/index/sid/824868/lang/sv  där det finns en länk att klicka på. 

> Vi hoppas att ni vill hjälpa oss uppmuntra och påminna studenterna att fylla i enkäten!

Bra om vi som tidigare år på något sätt kan få med nybörjarenkäten. Tidigare år har vi haft en kontrollfråga om enkäten för att försöka säkerställa att studenterna fyller i enkäten. Inte säkert att det är bästa sättet ... andra förslag?

**Comment by kamar535** [comment]
Kanske enklast att lägga till detta under modulen studenttjänster då den ligger först och det är bättre ju tidigare studenterna fyller enkäten.

**Comment by simonlovgren** [comment]
@kamar535 skall vi lägga till den som en frivillig del av uppgiften i studenttjänster?

**Comment by kamar535** [comment]
@simonlovgren Jag skulle föredra om vi lägger till den som en obligatorisk del av Studenttjänster. Kanske enklast att lägga till ett fält i inlämningsfilen `enkät:` där de sedan skall skriva ner något trivialt som de hittar i enkäten som "bevis" på att de läst och förhoppningsvis lämnat in den. Det är så vi gjort tidigare år och TekNat har varit mycket nöjda med den stora effekt detta haft på svarsfrekvensen.

**Comment by simonlovgren** [comment]
Om vi lägger in det som en del av inlämningsuppgiften är enkäten inte längre frivillig utan studenterna tvingas fylla i den, men Björn skriver:
>**Medverkan i enkäten är frivillig**, både för programmen **och för studenterna**...

**Comment by kamar535** [comment]
De behöver inte fylla i enkäten, endast läsa enkäten. Vi har gjort på liknade sätt i flera år och alla (speciellt de som analyserar enkäten) har varit mycket nöjda med den extremt höga svarsfrekvens som detta leder till. 

Vi kan givetvis lägga till information om att det är helt frivilligt att fylla i och skicka in enkäten men att det är mycket uppskattat för att Uppsala universitet skall kunna arbeta för att förbättra utbildningen, utbildningsinformation och mottagandet av nya studenter.

**Comment by kamar535** [comment]
@simonlovgren  Bra om vi kan få med detta asap. Enklast att lägga det sist i modulen Studenttjänster.

**Comment by simonlovgren** [comment]
yes, vi fixar att uppdatera uppgiften med formuläret tillsammans med rättningsmallen för studenttjänster.
