### ISSUE TITLE
Dedlines för inlämningar och kompletteringar

### ISSUE THREAD

**Issue by kamar535** [simonlovgren/introit-16#69]
Viktigt att tydligt kommunicera till studenter och kursansvariga om deadlines för inlämningar och kompletteringar. 

Förra året tror jag det var deadline för (första) inlämning en vecka efter det handledningstillfälle som hör till respektive uppgift. 

Sedan behövs en sista deadline för kompletteringar som gör det möjligt för höstens handledare att göra en sista omgång med rättning. Några dagar (eller en vecka) efter detta så avslutas handledarnas uppdrag.

Hur vill ni göra med deadlines i höst?

**Comment by simonlovgren** [comment]
Det spelar ingen roll, sätt dem som en del av introkursen så de passar där så kan vi skriva ut dem på de programspecifika sidorna. Det är ändå studentportalen deadlines och så kommer vara satta.

**Comment by simonlovgren** [comment]
> Visst kommer det finnas matris eller liknande som visar vilken modul som gäller för vilket programs olika pass med handledning?

Jag har lagt in tabeller över vilken modul som hålls i vilket pass i de programspecifika sidorna (som finns i branch material-infosida, alt PR #68). Där har jag enast indikerat vilket tillfälle som gäller för vardera obligatorisk modul. **Ex. från programsidan IT/KandDV:**
![cap](https://cloud.githubusercontent.com/assets/6557103/17894375/70b49eec-6949-11e6-8e63-c2512267b384.png)

> Då föreslår jag att deadline för första inlämning sätts till en vecka efter respektive uppgifts handledningstillfälle.

Låter bra, kör på det :)

> Enklast med en gemensam slutdeadline för kompletteringar för alla, förutom möjligen IT/KandDv som har fler pass. Mitt förslag är att sätta denna till en vecka efter sista passet med handledning/uppsamling sett över samtliga förutom IT/KandDv.

Inte alla klasser har sista tillfället samma vecka, men antar att du menar en vecka efter sista tillfället som finns i något schema (borträknat IT/KandDV)? I så fall kör på det :)

**Comment by kamar535** [comment]
> Inte alla klasser har sista tillfället samma vecka, men antar att du menar en vecka efter sista tillfället som finns i något schema (borträknat IT/KandDV)? I så fall kör på det :)

Precis så jag menade med frasen _"sett över samtliga förutom IT/KandDv"_ :-)

Sen separat sista deadline för IT/KandDv en vecka efter deras sista tillfälle med handledning.

**Comment by kamar535** [comment]
Jag har nu lagt till ett block för Introduktion till datorer i menyn på kurssidorna i Studentportalen för: 

- E/EI
- F
- IT/KandDv
- KandMa
- MI
- Q
- STS

I detta block finns en länk till http://www.it.uu.se/education/course/homepage/introdat/ht16/om/ samt inlämningar för programmets obligatoriska uppgifter. 

Deadlines för inlämning har sats till en vecka efter sista handledning av respektive uppgift för utbildningen då det skiljer rätt mycket mellan vissa utbildningar och det är bättre att hålla tempo på kurserna.

Sista deadline för komplettering har satts till två veckor efter sista tillfället (uppsamling) för utbildningen. 

ES hanteras helt i Fronter. 

W har jag ännu inte kunnat fixa då jag av någon anledning tappat behörighet i Studentportalen på Institutionen för geovetenskaper som ger kursen 1TV000. Jag återkommer så fort detta är åtgärdat.

**Comment by simonlovgren** [comment]
@kamar535 En av handledarna nämnde att W pluggar på/via SLU, så de kanske också har kursen i Fronter?

**Comment by kamar535** [comment]
@simonlovgren Det kan hända att de pluggar kurser vid SLU, dock ges kursen 1TV000 - Introduktion till miljö- och vattenteknik av Institutionen för geovetenskaper vid UU.

**Comment by simonlovgren** [comment]
ok
