### ISSUE TITLE
Studenttjänster - Korint och PayEx 

### ISSUE THREAD

**Issue by kamar535** [simonlovgren/introit-16#72]
På min fråga: 

> Hur kommer innestående medel på PayEx-konton att hanteras vid införandet av det nya systemet 2017: 

, har jag fått följande svar: 

> Hej 
> 
> Innestående medel på PayEx kommer att tillhöra studenten som det gör idag.
> 
> PayEx är en bank som ger möjlighet att ta ut pengar , föra över pengar eller att handla för pengarna på vissa butiker. Pressbyrån och 7-eleven som de största butikerna.
> 
> Pengar som finns kvar på studentens konto på PayEx när Korint läggs ned kommer inte att flyttas av Uppsala universitet eftersom vi inte har den möjligheten.
> 
> På grund av att PayEx tar en avgift för att ta ut och flytta pengar bör studenter inte sätta in mer pengar än som de kan förbruka.
> Det bör vi försöka informera mer om när vi har ett datum för avslut på Korint.
> 
> Nya upphandlingen, EduPrint, har överklagats men så snart den är klar och ett mer precist datum finns ska vi informera via webbsidan och helpdesk.
> 
> Hoppas att detta ger dig svar på din fråga.
> Om jag har uttryckt mig oklart så skicka en mail till eller att vi kan prata i telefon direkt, 018 471 6255.
> 
> 
> Mvh
> Uppsala universitet Servicedesk
> Anders Lundgren
> Korint 
> 
> support@korint.uu.se

**Comment by Kurogamu** [comment]
Ändrar formuleringen "osäkert" till "kvarvarande pengar går att ta ut, mot en avgift"
