### ISSUE TITLE
Rättningsmallar

### ISSUE THREAD

**Issue by simonlovgren** [simonlovgren/introit-16#76]
- [x] Studenttjänster
- [x] Excel
- [x] Linux
- [x] Terminalen
- [x] Latex
- [x] MATLAB
- [ ] Git

**Comment by Kurogamu** [comment]
Så, de vi avvaktar med nu är alltså studenttjänster och git pga materialändringar?

**Comment by simonlovgren** [comment]
Studenttjänster kommer nog vara rel. likadan med tillägg i mallen för formulärsvaret, men mallen för git kommer bli annorlunda om man också ska klona repot först om man rättar själva loggen?

**Comment by Kurogamu** [comment]
Då tar jag på mig terminalen och studenttjänster idag, efter att ha ordnat de fixar som ska ordnas :)

**Comment by simonlovgren** [comment]
ait :)  Jag sitter och kollar genom karls PR för tillfället. Kan skapa en rättningsmall till git efter den mergats

**Comment by Kurogamu** [comment]
Sååaaatteeeeeh, hur går  det med denna @simonlovgren ? Sista issuen kvar innan MVP ^^

**Comment by simonlovgren** [comment]
ohrite... yes, kan skriva ihop den idag. Har helt glömt det.

**Comment by simonlovgren** [comment]
@Kurogamu PR uppe för rättningsmall
