### ISSUE TITLE
Top-menyn och startsidan

### ISSUE THREAD

**Issue by kamar535** [simonlovgren/introit-16#77]
# Top-menyn

Jag vill att vi byter namn från **Om kursen** till **Om Introduktion till datorer**.

Jag vill ha följande ordning i top-menyn: Alla moduler, Programsidor, Om Introduktion till datorer, För handledare.

# Startsidan

Jag vill ha en kort text direkt under top-menyn och ovanför korten med moduler på startsidan. Denna text kan tas direkt från inledningen på sidan om.md

> Introduktion till datorer (också känt som dataproppen) är en del av ditt programs introduktionskurs. Till skillnad från matteproppen ger introduktion till datorer högskolepoäng.
> 
> Momentet är indelat i olika moduler och för varje modul finns en uppgift som skall lämnas in. När du blivit godkänd på uppgifterna är du också klar med detta kursmoment.

samt med följande något modifierade avslutning: 

Vilka moduler som ingår för just ditt program framgår på någon av programsidorna för E/EI, ES, F, IT/KandDv, KandMa, MI, Q, STS eller W. [länkar till respektive programsida]

Läs mer om Introduktion till datorer [här](./om.md).

**Comment by simonlovgren** [comment]
> Jag vill att vi byter namn från Om kursen till Om Introduktion till datorer.
Check

> Jag vill ha följande ordning i top-menyn: Alla moduler, Programsidor, Om Introduktion till datorer, För handledare.

Check. Jag har även gjort så att `alla moduler` endast syns när man är på en undersida för att alla knappar skall få plats på startsidan i och med det längre namnet enl. första punkten.

Jag jobbar på att lägga till en textruta som inte ser helt out-of-place ut.

**Comment by simonlovgren** [comment]
Textruta fixad och uppladdad.
