### ISSUE TITLE
Local build ==> 404 page not found 

### ISSUE THREAD

**Issue by kamar535** [simonlovgren/introit-16#83]
Efter:

```shelll
fetch upstream
git merge upstream/master
git make
git make server

scss -t compressed themes/introit16/static/scss/style.scss themes/introit16/static/css/style.css
hugo server
Started building site
0 of 2 drafts rendered
0 future content
40 pages created
2 non-page files copied
0 paginator pages created
0 tags created
0 categories created
in 54 ms
Watching for changes in /Users/karl/Teaching/Introduktion till datorer/2016/introit-16/{data,content,layouts,static,themes}
Serving pages from memory
Web Server is available at http://localhost:1313//www.it.uu.se/education/course/homepage/introdat/ht16/ (bind address 127.0.0.1)
Press Ctrl+C to stop
``` 

, får jag **404 page not found** på alla sidor, till exempel http://localhost:1313//www.it.uu.se/education/course/homepage/introdat/ht16/

**Comment by simonlovgren** [comment]
Jag har ställt in baseurl i `config.toml` för att stödja både http och https då det var några handledare som hade problem med att sidan inte laddade via https då baseurl var satt till http.

Det verkar krångla med utvecklingsservern, så jag har ställt om basurl och alla url:er till HTTPS iom att jag lagt upp en .htaccess-fil som dirigerar om alla HTTP till HTTPS för sidan.

Om du mergar med upstream nu skall det funka igen.
