### ISSUE TITLE
Besök på startföreläsning

### ISSUE THREAD

**Issue by kamar535** [simonlovgren/introit-16#93]
Tidigare år har handledarna gjort ett kort besök för att presentera sig och momentet Introduktion till datorer på respektive kurs startföreläsning. Men, jag vill minnas att vi inte diskuterat detta alternativt redan beslutat att inte prioritera detta i höst.

Helt ok att vi inte prioriterar detta i höst, jag vill bara vara säker på att jag inte missat något.

**Comment by simonlovgren** [comment]
Det är inget vi diskuterat/tänkt på och eftersom det nu är väldigt tight inpå handlednigstillfällen och startföreläsningarna är det trol. väldigt svårt att hinna få ut information m.m.

Det får nog bli så att det inte prioriteras utan får kommas ihåg till nästa år istället.

**Comment by kamar535** [comment]
Helt rätt prioriterat. Jag ville bara vara säker på att jag kom ihåg rätt. 

Jag har skickat ut info till kursansvariga så om årets upplägg så de kan ta upp det på sina respektive startföreläsningar.
