### ISSUE TITLE
Karl - push branch - permission denied

### ISSUE THREAD

**Issue by kamar535** [simonlovgren/introit-16#94]
Istället för att arbeta mot en egen fork vill jag testa att arbeta direkt med feature branches mot huvud-repot. Jag saknar dock rättigheter att göra detta, se nedan. 

```shell
$> git remote -v
origin 	https://github.com/simonlovgren/introit-16.git (fetch)
origin 	https://github.com/simonlovgren/introit-16.git (push)
$> git branch -v
  master                    471f826 added föreläsningsmaterial-link
* om-inlämning-och-framsteg 0bca897 info om inlämning i Studentportalen
$> git push --set-upstream origin om-inlämning-och-framsteg
remote: Permission to simonlovgren/introit-16.git denied to kamar535.
fatal: unable to access 'https://github.com/simonlovgren/introit-16.git/': The requested URL returned error: 403
```

**Comment by kamar535** [comment]
Ping @simonlovgren

**Comment by simonlovgren** [comment]
Ok. Då lägger vi till dig i repot.

Arbetsflödet som gäller är att **all utveckling sker i branches** och **ingen pushar till master**. 

När en feature eller justering är klar att mergas med master skapas en PR för med kort förklaring och ev. referenser till issues den hanterar. För att referera en issue, PR eller annat på GitHub skriver man `#` följt av siffran för issuen eller PR:en (t.ex. #94 refererar till denna issue).

Om det är så att en PR löser någon eller några issues kan man lägga till kommentarer som automatiskt stänger dessa issues vid merge. Detta görs genom att skriva ett av [nyckelorden för automatisk stängning av issues](https://help.github.com/articles/closing-issues-via-commit-messages/). För exempel på detta kan du kolla på beskrivningen i PR #100. Detta är väldigt smidigt då man slipper gå genom issues för att se vilka man fixat sedan tidigare.

Referenser till issues funkar även i commit-meddelanden, vilket ibland kan vara användbart för att slippa .

**Comment by simonlovgren** [comment]
@kamar535 invite till repot skickat
