### ISSUE TITLE
Skillnad mellan teknats och studentportalens schema

### ISSUE THREAD

**Issue by Kurogamu** [simonlovgren/introit-16#96]
Kan vara bra att nämna, att studentportalen utgår från registrerade kurser medan teknat kör på rekommenderade för program (beroende på hur man väljer dårå)

**Comment by simonlovgren** [comment]
@kurogamu är det i uppgiften eller i infosidan du tänker detta skall nämnas?

**Comment by Kurogamu** [comment]
Infosidan blir nog bäst ^^
