### ISSUE TITLE
Kaffe på passerkort/campuskort

### ISSUE THREAD

**Issue by kamar535** [simonlovgren/introit-16#98]
Alla handledare som finns på listan https://docs.google.com/spreadsheets/d/1nMCeIvNau7xWTFJ4AEja5L2x-aaJrQuzYgJ28w4WHQs/edit#gid=562541617 kan nu gå till luckan **nycklar/passerkort** på Ångströms och få kaffe inlagt på sitt passerkort/campuskort. Kaffe kan sedan hämtas kostnadsritt i maskinerna vid Café Ångström fram till mitten av oktober.

**Comment by Kurogamu** [comment]
Bästa nyheten idag!

2016-08-31 7:30 GMT+00:00 Karl Marklund <notifications@github.com>:

**Comment by simonlovgren** [comment]
check, testat att det gick hämta ut och har nu mailat alla handledare.
